[build]
  command = "npm run build"
  publish = "build"
  base = "/Blog"  # Updated to include a leading slash

[[redirects]]
  from = "/*"
  to = "/index.html"  # Update the "to" value to include "/Blog/"
  status = 200
  force = true

[[redirects]]
  from = "/Blog/*"
  to = "/Blog/index.html"
  status = 200
  force = true
