[build]
  command = "npm run build"
  publish = "build"
  base = "/Blog"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/Blog/*"
  to = "/Blog/index.html"
  status = 200
  force = true
